# Generated by Django 4.0.5 on 2022-06-11 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('minister_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('preacher', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, choices=[('Koinonia, Zaria', 'Koinonia, Zaria'), ('Koinonia, Abuja', 'Koinonia, Abuja'), ('External Ministration', 'External Ministration')], max_length=200)),
                ('message_year', models.CharField(blank=True, max_length=4, null=True)),
                ('message_audio', models.FileField(upload_to='audio/')),
                ('message_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='message-img/')),
                ('message_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ManyToManyField(blank=True, to='website.category')),
                ('minister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.minister')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
